//获取页面元素
var $is=$('.slider .basic-information i');

$(document).ready(function(){
    for(var i=0; i<$is.length;i++){
        (function (index) {
            //webstrom
            $($is[0]).jQMeter({
                goal:'100%',
                raised:'80%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //sublime
            $($is[1]).jQMeter({
                goal:'100%',
                raised:'60%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //ps
            $($is[2]).jQMeter({
                goal:'100%',
                raised:'60%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //jq
            $($is[3]).jQMeter({
                goal:'100%',
                raised:'80%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //zepto
            $($is[4]).jQMeter({
                goal:'100%',
                raised:'80%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //angular
            $($is[5]).jQMeter({
                goal:'100%',
                raised:'60%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //react
            $($is[6]).jQMeter({
                goal:'100%',
                raised:'40%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //vue
            $($is[7]).jQMeter({
                goal:'100%',
                raised:'50%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //原生JS
            $($is[8]).jQMeter({
                goal:'100%',
                raised:'80%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //node
            $($is[9]).jQMeter({
                goal:'100%',
                raised:'40%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //ejs
            $($is[10]).jQMeter({
                goal:'100%',
                raised:'40%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //yeoman
            $($is[11]).jQMeter({
                goal:'100%',
                raised:'40%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
            //webpack
            $($is[12]).jQMeter({
                goal:'100%',
                raised:'50%',
                meterOrientation:'horizontal',
                width:'100%',
                height:'15px',
                bgColor:'#CCC',
                barColor:'#68b020'
            });
        })(i);
    }
});


